apiVersion: v1
kind: PersistentVolume
metadata:
  name: db1
  labels:
    vol: database
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/db/db1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db2
  labels:
    vol: database
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/db/db2
