# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
#VAGRANTFILE_API_VERSION = "2"

#$script = <<SCRIPT
# TODO: Put your install script here.
#SCRIPT

#Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  # Official boxes are here: https://atlas.hashicorp.com/boxes/search
  # Additional boxes here: http://www.vagrantbox.es/
  #config.vm.box = "ubuntu/trusty64"
  #config.vm.box = "hashicorp/precise64"

  # You can shell scripts when `vagrant up` or `vagrant provision` is run.
  # Just put scripts in the same directory as this `Vagrantfile`.
  #config.vm.provision "shell", privileged: false, path: "vagrant-bootstrap.sh"
  # You can do multiple scripts, if you want:
  #config.vm.provision "shell", privileged: false, path: "vagrant-bootstrap2.sh"
  #config.vm.provision "shell", privileged: true, inline: $script

  # Port forwarding examples
  # Just in case you need to run a database server, web server, etc.
  #config.vm.network "forwarded_port", guest: 8080, host: 8080
  #config.vm.network "forwarded_port", guest: 5000, host: 5000
  #config.vm.network "forwarded_port", guest: 35357, host: 35357

  # Mem/cpu config example.
  # If you need more CPUs/RAM, uncomment the next 4 lines and edit as needed.
  #config.vm.provider "virtualbox" do |v|
  #  v.memory = 1024
  #  v.cpus = 2
  #end
  
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
    v.memory = 8192
    v.cpus = 2
end
