# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-3
spec:
  containers:
  - name: sec-ctx-3
    image: gcr.io/google-samples/node-hello:1.0
