# Server Packages that Need to Be Installed for Server Repository Administration
choco install googlechrome -y
choco install firefox -y
choco install openssh -y
choco install git -y
choco install 7zip -y
choco install putty.install -y
choco install vim -y
choco install vagrant -y
choco install python -y
choco install dotnetcore-sdk -y
choco install ruby -y
choco install winscp -y
choco install awscli -y
choco install cygwin -y
choco install virtualbox -y
choco install chocolateygui -y
choco install azure-cli -y
choco install golang -y
choco install keepass -y
choco install sourcetree -y
choco install openssl.light -y
choco install prometheus-wmi-exporter.install -y
choco install windirstat -y
choco install citrix-receiver -y
choco install sqlserver-odbcdriver -y
choco install kubernetes-cli -y
choco install openvpn -y
choco install postman -y
choco install mysql.workbench -y
choco install gpg4win -y
choco install mongodb -y
choco install jenkins-x -y
choco install powerbi -y
choco install postgresql -y
choco install rabbitmq -y
choco install flashplayerppapi -y
choco install flashplayerplugin -y
choco install flashplayeractivex -y
choco install windows-admin-center -y
choco install anaconda3 -y
choco install wget -y
choco install curl -y
choco install filezilla.server -y
