# Server Packages that Need to Be Installed for Server Repository Administration
choco install googlechrome
choco install firefox
choco install openssh
choco install git
choco install 7zip
choco install putty.install
choco install vim
choco install vagrant
choco install python
choco install dotnetcore-sdk
choco install ruby
choco install winscp
choco install awscli
choco install cygwin
choco install virtualbox
choco install chocolateygui
choco install azure-cli
choco install golang
choco install keepass
choco install sourcetree
choco install openssl.light
choco install prometheus-wmi-exporter.install
choco install windirstat
choco install citrix-receiver
choco install sqlserver-odbcdriver
choco install kubernetes-cli
choco install openvpn
choco install postman
choco install mysql.workbench
choco install gpg4win
choco install mongodb
choco install jenkins-x
choco install powerbi
choco install postgresql
choco install rabbitmq
choco install flashplayerppapi
choco install flashplayerplugin
choco install flashplayeractivex
choco install windows-admin-center
choco install anaconda3
choco install wget
choco install curl
choco install filezilla.server

