apiVersion: v1
kind: Service
metadata:
  name: ghost-service
spec:
  #type: LoadBalancer
  type: NodePort
  ports: 
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ghost
