kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: replicated
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd
volumeBindingMode: WaitForFirstConsumer
