apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      - name: ghost
        image: ghost:1.24
        ports:
        - containerPort: 2368
        env:
        - name: GHOST_DB_USER
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: username
        - name: GHOST_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: password
        - name: GHOST_DB_NAME
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: username
#       volumeMounts:
#        - name: config-js
#          mountPath: /var/lib/ghost/content

      volumes:
      - name: nginx-conf
        configMap:
          name: ghost-config
          items:
          - key: nginx-ghost.conf
            path: ghost.conf
      - name: config-js
        configMap:
          name: ghost-config
          items:
          - key: ghost-config.js
            path: config.js
