Vagrant.configure(2) do |config|
  config.vm.box = 'travis-ci/ci-minimal-trusty64'

  config.ssh.username = 'travis'
  config.ssh.password = 'travis'

  config.vm.synced_folder '.', '/vagrant', disabled: true
end
