# https://kubernetes.io/docs/reference/access-authn-authz/authorization/#authorization-modules
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectAccessReview
spec:
  resourceAttributes:
    namespace: development
    resource: pods
    subresource: exec
    verb: create
