apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  containers:
  - image: alpine
    command:
      - nc
      - -p
      - '80'
      - -lke
      - echo
      - -ne
      - 'HTTP/1.0 200 OK\nContent-Length: 13\n\nHello World!\n'
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: alpine
spec:
  type: "NodePort"
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8000
  selector:
    test: alpine
